Create README.md
logzio/logzio-jumpcloud pull request #1
Opened 2023-05-08 14:02 UTC by eranp22

2023-05-14 11:44 UTC, ShiranAvidov requested changes

2023-05-14 11:44 UTC, ShiranAvidov commented on README.md
> +| time_interval | The time interval for querying the JumpCloud API in minutes. | Required | Equals to nothing as Default 5m |
Set time_interval to Optional and in default write 5m

2023-05-14 11:44 UTC, ShiranAvidov commented on README.md
> + token: "Logzio_Token"
```suggestion
 token: "<<LOGZIO_TOKEN>>"
```

2023-05-14 11:44 UTC, ShiranAvidov commented on README.md
> +     token: "jumpcloud_api_token"
```suggestion
     token: "<<JUMPCLOUD_API_TOKEN>>"
```

2023-05-14 11:44 UTC, ShiranAvidov commented on README.md
> +Every time interval, events exported from Jumpcloud API is in the configuration and sends it to Logz.io.
```suggestion
Collects Jumpcloud events every time interval, using the Jumpcloud API given in the configuration, and sends them to Logz.io.
```

2023-05-14 13:19 UTC, eranp22 reviewed
README.md update

2023-05-15 08:40 UTC, ShiranAvidov approved these changes

2023-05-15 08:55 UTC, eranp22 commented
Create README.md

2023-05-15 08:56 UTC, merged